version: '3.7'

services:
  radarr:
    container_name: pidownload-radarr
    image: dtroncy/rpi-radarr:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOWNLOADS_FOLDER}:/volumes/download
      - ${MOVIES_FOLDER}:/volumes/media
      - ./docker/radarr_config:/volumes/config
    ports:
      - 7878:7878

  transmission:
    container_name: pidownload-transmission
    image: jaymoulin/transmission
    restart: unless-stopped
    command: my-daemon -c /to_download -w /output -T -b --no-incomplete-dir -O -Y -a '*.*.*.*' --utp -M -ep -f -g /config
    ports:
      - 9091:9091
      - 51413:51413
    volumes:
      - /data/transmission/to_download:/to_download
      - ${DOWNLOADS_FOLDER}:/output
      - ./docker/transmission_config:/config

  rpi-samba:
    container_name: pidownload-samba
    image: trnape/rpi-samba
    restart: unless-stopped
    volumes:
      - ${DOWNLOADS_FOLDER}:/share/data
    entrypoint: ["/run.sh", "-u", "guest:guest", "-s", "Raspberry:/share/data:rw:guest"]
    ports:
      - '445:445'
      - '139:139'
      - '137:137/udp'
      - '138:138/udp'

  minidlna:
    container_name: pidownload-minidlna
    image: cytomich/rpi-docker-minidlna
    restart: unless-stopped
    volumes:
      - ${MOVIES_FOLDER}:/media/movies
      - ${SERIES_FOLDER}:/media/series
    environment:
      - MINIDLNA_MEDIA_DIR=V,/media
      - MINIDLNA_PORT=8200
      - MINIDLNA_FRIENDLY_NAME=raspberry
    network_mode: "host"
    ports:
      - '8200:8200'
      - '1900:1900/udp'
