version: '3.7'

services:
  #Content providers
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./docker/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    container_name: pidownload-radarr
    image: lscr.io/linuxserver/radarr
    restart: unless-stopped
    volumes:
      - ${DOWNLOADS_FOLDER}:/download
      - ${MOVIES_FOLDER}:/movies
      - ./docker/radarr_config:/config
    ports:
      - 7878:7878

  sonarr:
    container_name: pidownload-sonarr
    image: lscr.io/linuxserver/sonarr
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./docker/sonarr_config:/config
      - ${SERIES_FOLDER}:/tv
      - ${DOWNLOADS_FOLDER}:/download
    ports:
      - 8989:8989

  #Subtitles
  bazarr:
    container_name: pidownload-bazarr
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./docker/bazarr_config:/config
      - ${MOVIES_FOLDER}:/movies #optional
      - ${SERIES_FOLDER}:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

  #Downloaders
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: pidownload-qbittorrent
    environment:
      - TZ=Europe/Berlin
      - WEBUI_PORT=9091
    volumes:
      - ./docker/qbittorrent_config:/config
      - ${DOWNLOADS_FOLDER}:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 9091:9091
    restart: unless-stopped

  jdownloader:
    container_name: pidownload-jdownloader
    image: jaymoulin/jdownloader
    restart: unless-stopped
    volumes:
      - ${DOWNLOADS_FOLDER}:/opt/JDownloader/Downloads
      - ./docker/jdownloader_config:/opt/JDownloader/cfg
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYJD_DEVICE_NAME: raspberry
      XDG_DOWNLOAD_DIR: /opt/JDownloader/Downloads
    ports:
      - 3129:3129

  #Network sharers
  samba:
    container_name: samba
    image: lordpedal/samba
    restart: unless-stopped
    volumes:
       - ${DOWNLOADS_FOLDER}:/lordpedal
    ports:
      - '445:445'
      - '139:139'
      - '137:137/udp'
      - '138:138/udp'

  minidlna:
    container_name: pidownload-minidlna
    image: lordpedal/minidlna
    restart: unless-stopped
    volumes:
      - ${MOVIES_FOLDER}:/media/movies
      - ${SERIES_FOLDER}:/media/series
    environment:
      - MINIDLNA_MEDIA_DIR=V,/media
      - MINIDLNA_PORT=8200
      - MINIDLNA_FRIENDLY_NAME=minipc
      - MINIDLNA_INOTIFY=yes
    network_mode: "host"

  plex:
    container_name: pidownload-plex
    image: lscr.io/linuxserver/plex
    restart: unless-stopped
    volumes:
      - ./docker/plex_config:/config
      - ${SERIES_FOLDER}:/tv
      - ${MOVIES_FOLDER}:/movies
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    network_mode: "host"
    privileged: true
    ports:
      - '32400:32400'

  jellyfin:
      image: lscr.io/linuxserver/jellyfin
      container_name: pidownload-jellyfin
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Berlin
        - JELLYFIN_PublishedServerUrl=192.168.1.141
      volumes:
        - ./docker/jellyfin_config:/config
        - ${SERIES_FOLDER}:/data/tvshows
        - ${MOVIES_FOLDER}:/data/movies
        - /opt/vc/lib:/opt/vc/lib
      ports:
        - '8096:8096'
        - '7359:7359/udp'
      devices:
        - /dev/dri:/dev/dri
          # - /dev/video10:/dev/video10
          # - /dev/video11:/dev/video11
          #- /dev/video12:/dev/video12
      restart: unless-stopped

networks:
  default:
    name: coolify
    external: true
