version: '3.7'

services:
  #Content providers
  jackett:
    container_name: pidownload-jackett
    image: ghcr.io/linuxserver/jackett
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - AUTO_UPDATE=true
      # - RUN_OPTS=<run options here>
    volumes:
      - ${DOWNLOADS_FOLDER}:/downloads
      - ./docker/jackett_config:/config
    ports:
      - 9117:9117

  radarr:
    container_name: pidownload-radarr
    image: dtroncy/rpi-radarr:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOWNLOADS_FOLDER}:/volumes/download
      - ${MOVIES_FOLDER}:/volumes/media
      - ./docker/radarr_config:/volumes/config
    ports:
      - 7878:7878

  #Downloaders
  transmission:
    container_name: pidownload-transmission
    image: jaymoulin/transmission
    restart: unless-stopped
    command: my-daemon -c /to_download -w /output -T -b --no-incomplete-dir -O -Y -a '*.*.*.*' --utp -M -ep -f -g /config
    ports:
      - 9091:9091
      - 51413:51413
    volumes:
      - /data/transmission/to_download:/to_download
      - ${DOWNLOADS_FOLDER}:/output
      - ./docker/transmission_config:/config

  jdownloader:
    container_name: pidownload-jdownloader
    image: jaymoulin/jdownloader
    restart: unless-stopped
    volumes:
      - ${DOWNLOADS_FOLDER}:/opt/JDownloader/Downloads
      - ./docker/jdownloader_config:/opt/JDownloader/cfg
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYJD_DEVICE_NAME: raspberry
      XDG_DOWNLOAD_DIR: /opt/JDownloader/Downloads
    ports:
      - 3129:3129

  #Network sharers
  rpi-samba:
    container_name: pidownload-samba
    image: trnape/rpi-samba
    restart: unless-stopped
    volumes:
      - ${DOWNLOADS_FOLDER}:/share/data
    entrypoint: [ "/run.sh", "-u", "guest:guest", "-s", "Raspberry:/share/data:rw:guest" ]
    ports:
      - '445:445'
      - '139:139'
      - '137:137/udp'
      - '138:138/udp'

  minidlna:
    container_name: pidownload-minidlna
    image: cytomich/rpi-docker-minidlna
    restart: unless-stopped
    volumes:
      - ${MOVIES_FOLDER}:/media/movies
      - ${SERIES_FOLDER}:/media/series
    environment:
      - MINIDLNA_MEDIA_DIR=V,/media
      - MINIDLNA_PORT=8200
      - MINIDLNA_FRIENDLY_NAME=raspberry
    network_mode: "host"
    ports:
      - '8200:8200'
      - '1900:1900/udp'

  plex:
    container_name: pidownload-plex
    image: lscr.io/linuxserver/plex
    restart: unless-stopped
    volumes:
      - ./docker/plex_config:/config
      - ${SERIES_FOLDER}:/tv
      - ${MOVIES_FOLDER}:/movies
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    network_mode: "host"
    privileged: true
    ports:
      - '32400:32400'
