version: '3.7'

services:
  radarr:
    container_name: pidownload-radarr
    image: dtroncy/rpi-radarr:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/radarr_config:/volumes/config
      #folder to movies
      - /mnt/usb-disk/pidownloads/pelis:/volumes/media
      #folder to downloads
      - /mnt/usb-disk/pidownloads:/volumes/download
    ports:
      - 7878:7878