version: '3.7'

services:
  #Content providers
  jackett:
    container_name: pidownload-jackett
    image: ghcr.io/linuxserver/jackett
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - AUTO_UPDATE=true
      # - RUN_OPTS=<run options here>
    volumes:
      - ${DOWNLOADS_FOLDER}:/downloads
      - ./docker/jackett_config:/config
    ports:
      - 9117:9117

  radarr:
    container_name: pidownload-radarr
    image: lscr.io/linuxserver/radarr
    restart: unless-stopped
    volumes:
      - ${DOWNLOADS_FOLDER}:/download
      - ${MOVIES_FOLDER}:/movies
      - ./docker/radarr_config:/config
    ports:
      - 7878:7878

  sonarr:
    container_name: pidownload-sonarr
    image: lscr.io/linuxserver/sonarr
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./docker/sonarr_config
      - ${SERIES_FOLDER}:/tv
      - ${DOWNLOADS_FOLDER}:/download
    ports:
      - 8989:8989

  #Downloaders
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: pidownload-qbittorrent
    environment:
      - TZ=Europe/Berlin
      - WEBUI_PORT=9091
    volumes:
      - ./docker/qbittorrent_config:/config
      - ${DOWNLOADS_FOLDER}:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 9091:9091
    restart: unless-stopped

  jdownloader:
    container_name: pidownload-jdownloader
    image: jaymoulin/jdownloader
    restart: unless-stopped
    volumes:
      - ${DOWNLOADS_FOLDER}:/opt/JDownloader/Downloads
      - ./docker/jdownloader_config:/opt/JDownloader/cfg
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYJD_DEVICE_NAME: raspberry
      XDG_DOWNLOAD_DIR: /opt/JDownloader/Downloads
    ports:
      - 3129:3129

  #Network sharers
  rpi-samba:
    container_name: pidownload-samba
    image: trnape/rpi-samba
    restart: unless-stopped
    volumes:
      - ${DOWNLOADS_FOLDER}:/share/data
    entrypoint: [ "/run.sh", "-u", "guest:guest", "-s", "Raspberry:/share/data:rw:guest" ]
    ports:
      - '445:445'
      - '139:139'
      - '137:137/udp'
      - '138:138/udp'

  minidlna:
    container_name: pidownload-minidlna
    image: cytomich/rpi-docker-minidlna
    restart: unless-stopped
    volumes:
      - ${MOVIES_FOLDER}:/media/movies
      - ${SERIES_FOLDER}:/media/series
    environment:
      - MINIDLNA_MEDIA_DIR=V,/media
      - MINIDLNA_PORT=8200
      - MINIDLNA_FRIENDLY_NAME=raspberry
    network_mode: "host"
    ports:
      - '8200:8200'
      - '1900:1900/udp'

  plex:
    container_name: pidownload-plex
    image: lscr.io/linuxserver/plex
    restart: unless-stopped
    volumes:
      - ./docker/plex_config:/config
      - ${SERIES_FOLDER}:/tv
      - ${MOVIES_FOLDER}:/movies
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    network_mode: "host"
    privileged: true
    ports:
      - '32400:32400'
